### ISSUE TITLE
Allow to merge duplicate on import

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-contacts#103]
Reported by a user [in the forum](https://forum.cozy.io/t/bug-import-vcard-bug-graphique-et-probleme-doublons/798/2)

For now, when importing, if we find a contact already in data system, we just discard the new one. This is annoying, as some information in the card of the duplicate may be lost.
We should find a way to merge the new contact into the existing one.

See https://github.com/cozy/cozy-contacts/blob/809f6ef47aea5f9b5560ab88c459c16ca57fb6bd/server/controllers/contact.coffee#L42-L58

**Comment by tetrakos** [comment]
Hi,
I'm the upcited user ;)

Please notice that two contacts may have the same firstname and lastname. Hence, what is detected as a duplicate can be intentional and the two contacts should not be merged. Also, thunderbird only accepts 2 emails addresses per contact which leads to several cards per contact.

Maybe, you could import the contacts without merging and then run a duplicate finder which asks the user if the found duplicates should be merged.

**Comment by clochix** [comment]
Also see #88

**Comment by poupotte** [comment]
This issue is fixed with new version.
