### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-contacts#45]
* Special chars are not recognized.
* Can't import pictures.

**Comment by Beast141** [comment]
I can see pictures are able to be imported now

**Comment by jsilvestre** [comment]
What about special chars, @frankrousseau ?

**Comment by Beast141** [comment]
Oh yes special characters doesnt seem like they work either
Because when importing the contact with special characters then it only recognizes the number on import.. without the name.

**Comment by clochix** [comment]
The problem with "special chars" may be related to #44

**Comment by aenario** [comment]
Most of special characters encoding issues should have been fixed by : https://github.com/cozy/cozy-vcard/commit/9e243bc1783b90ee6014053d785dc79625892419

Which is part of cozy-contact v1.1.0
@Beast141 , could you test if the issue is solved for you ?

Otherwise, we'd appreciate if you can provide us with a example of a broken vcard. (in this thread or by mail at romain@cozycloud.cc if you prefer not make it public)

**Comment by clochix** [comment]
@Beast141 Have you been able to test with Cozy-contact 1.1.0 ? Can we close this ?

**Comment by Beast141** [comment]
@clochix sorry for the delay. As far as i can tell i havent had any special chars issues at the moment. Im going to do a test import with some new ascii chars to see if it will do it again. Il let you know over the weekend before you close this.

**Comment by clochix** [comment]
Thanks @Beast141 ☺

**Comment by Beast141** [comment]
@clochix 
Perfect - it all works with special chars!! you may close this.
Thanks for support!

**Comment by clochix** [comment]
Thanks for testing !
