### ISSUE TITLE
Select all contacts

### ISSUE THREAD

**Issue by whiver** [cozy/cozy-contacts#450]
Hi,
I imported a vcf file in cozy-contacts which seems to be an old version, so I would like to remove all the already imported contacts and reimport my new file.
Is there a way to select all contacts at once? Because it's tedious to select a few hundreds of contacts one by one :stuck_out_tongue:

Thanks!

**Comment by clochix** [comment]
Hello @whiver ,

For now, it's not possible to select all contacts at once.
If you're hosted on our platform, just drop a mail at support at cozycloud.cc, and I will drop drop your contact database, so you can restart the import from scratch.

**Comment by whiver** [comment]
Thanks for your help! I'll do that :)

**Comment by whiver** [comment]
Could you explain why you are closing this ticket? Has it been implemented? Because I still don't see it in the prod version.

**Comment by JF-Cozy** [comment]
Yes of course, very sorry to have closed the inssue savagely.

The ability to select multiple contacts is unfortunately not implemented since February 2019, and probably won't be in the near future. So the issue is closed to clean up the repository, this improvement is not a priority.

On the other hand the idea is kept in our backlog, so it can be prioritized in due time.

Anyway, a big thank you for your interest in Cozy !

**Comment by whiver** [comment]
Alright, thank you for the explanation 🙂
