### ISSUE TITLE
Picture is not supported in contact import/export

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-contacts#53]
Photo field should be included to the export.

Import should hande picture import too.

**Comment by jsilvestre** [comment]
Is it not working or not existing?

Because it should be at least present (and it was working last time I tried):
* https://github.com/cozy/cozy-contacts/blob/master/server/models/contact.coffee#L58-L60 (export)
* https://github.com/cozy/cozy-contacts/blob/master/client/app/models/contact.coffee#L339-L348 (import)

**Comment by frankrousseau** [comment]
Sorry it was a version problem.
